### ISSUE TITLE
Deleting a clone stops its sounds

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#949]
### Expected Behavior

In Scratch 2.0, if you start a sound in a clone, then delete the clone, and the sound will continue to play.

### Actual Behavior

Currently in 3.0, because clones have their own audio players which get disposed on clone delete, the sound stops.

### Steps to Reproduce

The meow should play when you create a clone:

![image](https://user-images.githubusercontent.com/567844/36678658-52816ccc-1adf-11e8-9852-dadbd83ba065.png)

### Operating System and Browser

Mac OS 10.13.2 Chrome 64

**Comment by ericrosenbaum** [comment]
After discussion with @thisandagain we realized that getting this to work as in 2.0 (i.e. sounds played by clones continue after the clone is deleted) will require a re-factor in scratch-audio:

- We'd merge AudioPlayer and SoundPlayer into a single SoundPlayer class which manages its own audio effects chain (volume and pan effect nodes). This may mean we're creating more audio nodes than before, but probably not (you're more likely to have a lot of clones at once than a lot of different sounds playing at once).
- Every sound would have a single SoundPlayer (created on demand, and deleted when the sound ends). 
- The sprite would manage an array of SoundPlayers, which would be accessed by a clone when it wants to play a sound (much like the current activeSoundPlayers array).
- When a clone starts a sound, or updates an effect value (volume, pan, or pitch), it would request its parent sprite to do so.
- When the parent sprite receives a request to update an effect value, it needs to apply this update to all sounds currently being played by that clone. This means we'd need some kind of ID system (do clones have IDs already?)

**Comment by TheLogFather** [comment]
Just a quick note that the above behaviour in Scratch 2 is different if the sound is played "until done".

In that case, deleting the clone *does* stop the sound. (That's because the script is still running, and stopping the script, when the clone gets deleted, also stops the sound currently being played by that script.)

**Comment by TheLogFather** [comment]
Actually, it's worth taking a look at this old project of mine:
https://scratch.mit.edu/projects/24414513
It uses clones to allow independent control (volume, stop/start) over sounds playing simultaneously.

Now compare with Scratch 3 preview:
https://preview.scratch.mit.edu/#24414513

(I think it'd be worth adding the above project for compatibility-testing – and not just for the sounds...)

**Comment by ericrosenbaum** [comment]
Fixed!

**Comment by TheLogFather** [comment]
This is still not quite working correctly. (EDIT: OTOH, maybe it is – but see next comment.)

Here's a simple test project:
https://preview.scratch.mit.edu/#237881668

It seems as though the notes for all clones of a sprite stop when one clone gets deleted...?

As mentioned [above](https://github.com/LLK/scratch-vm/issues/949#issuecomment-377959774), it's worth trying out https://scratch.mit.edu/projects/24414513 as a test project for the sound system in Scratch 3.

**Comment by TheLogFather** [comment]
Actually, looking more carefully, are all the instruments 'clipped' to fade away after some (fairly short) time in Scratch 3?

In Scratch 2 several of the instruments don't fade (e.g. organ, cello, synth lead/pad), so you can play a note from them for as long as you want (unlike some other instruments, such as piano, guitar, etc., which fade away).

The notes in the above test project don't last that long before fading to nothing, so I think that's what's happening (rather than the clone deletion causing problems)...?

**Comment by ericrosenbaum** [comment]
Hi @TheLogFather- Right, I think you are describing an unrelated issue. Clone deletion doesn't effect sounds played by the music extension. 

Basically, the music extension's instruments have a maximum duration, unlike in Scratch 2.0. This was a compromise that we made so that we could use a simpler system to synthesize their sounds (playing time-stretched samples, instead of using samples with loop points). If you'd like you can file an issue about the maximum duration of some of the instruments.

**Comment by TheLogFather** [comment]
OK, I see – I'll take a closer look and probably do that.

However, I notice now that a clone's sound started with "play sound *until done*" now no longer gets stopped when a clone is deleted in Scratch 3, which (as I mentioned [above](
https://github.com/LLK/scratch-vm/issues/949#issuecomment-377954406)) is not what happens in Scratch 2.

Note that the difference (in Scratch 2) is down to whether or not the script was still running – if so (i.e. if playing "until done") then the sound gets stopped when the clone is deleted because the script that's still playing that sound gets stopped.

(Similarly, in Scratch 2, "stop other scripts in sprite" stops a sound that's playing "until done" – no clones needed to test this one and see the behaviour in Scratch 3 is different...)
